all: # or individual group names
  hosts:
    mail.example.com:
      ansible_host: mail.example.com
      ansible_port: 22
  children:
    webservers:
      hosts:
        foo.example.com: # could also be individual name
          ansible_host: foo.example.com
          ansible_port: 22
        bar.example.com:
          ansible_host: bar.example.com
          ansible_port: 22
    dbservers:
      hosts:
        one.example.com:
          ansible_host: one.example.com
          ansible_port: 22
        two.example.com:
          ansible_host: two.example.com
          ansible_port: 22
        three.example.com:
          ansible_host: three.example.com
          ansible_port: 22

# referring to https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups